# Generated by Django 4.2.5 on 2023-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='condition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='datetime_in',
            field=models.DateTimeField(null=True, verbose_name='Date device in'),
        ),
    ]
