# Generated by Django 4.2.5 on 2023-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_audit_condition_alter_audit_datetime_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
